### ISSUE TITLE
Inquiry Regarding Nya-Engine Documentation | No Issue, just a way to reach u

### ISSUE THREAD

**Issue by AnasElii** [weimingtom/lua40mod#1]
I hope it's appropriate to reach out via GitHub Issues regarding Nya-Engine documentation.

I've been exploring Nya-Engine and find it to be a remarkable tool. However, in my quest to understand its full potential, I'm on the lookout for any documentation that may be available. Could you kindly guide me on where I can find comprehensive documentation for Nya-Engine?

**Comment by weimingtom** [comment]
Sorry, I don't know more than you. If you can't find any better information about Nya-Engine in my github, I can't help you about it.

**Comment by AnasElii** [comment]
thanks for the reply.
